name: Deploy to Droplet

on:
  push:
    branches: ["master"]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Deploy app
        run: doctl compute ssh ubuntu --ssh-user osso --ssh-command "sh ~/scripts/deploy-discord-bot.sh"
