name: Deploy to Droplet

on:
  push:
    branches: ["master"]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Deploy app
        run: doctl compute ssh ubuntu --ssh-user osso --ssh-command "sh ~/scripts/deploy-discord-bot.sh"
